[env:mik32v2]
platform = MIK32
board = mik32v2_elbear_8mb
framework = framework-mik32v2-sdk
board_build.ldscript=spifi
monitor_speed = 115200
;-Wdouble-promotion - выдавать передупреждение при неявном преобразовании к double
build_flags = -fsingle-precision-constant -Wdouble-promotion -v
monitor_filters = direct, time, default, send_on_enter